apiVersion: v1
kind: Service
metadata:
  name: service-two
  labels:
    {{- include "services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service_two.type }}
  ports:
    - port: {{ .Values.service_two.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: service-two
