apiVersion: v1
kind: Service
metadata:
  name: service-one
  labels:
    {{- include "services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service_one.type }}
  ports:
    - port: {{ .Values.service_one.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: service-one
