apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: service-gateway
  namespace: service
spec:
  selector:
    # app: istio-ingressgateway
    istio: ingressgateway
  servers:
    - hosts:
        - domain.example.com

      port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true

    - hosts:
        - domain.example.com

      port:
        number: 443
        name: https
        protocol: HTTPS

      tls:
        mode: SIMPLE
        credentialName: ingress-tls-cert
