kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-product
  namespace: service
  labels:
    app: product
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
        version: v1
    spec:
      containers:
        - name: service-one
          image: xuxant/service-one
          ports:
            - name: application
              containerPort: 5000
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-store
  namespace: service
  labels:
    app: store
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
        version: v1
    spec:
      containers:
        - name: service-two
          image: xuxant/service-two
          ports:
            - name: application
              containerPort: 5000
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
